Update patch set 1
Patch Set 1:

Original driver was failing here:
> ../../../../../../kernel/xiaomi/msm8996/drivers/video/msm/mdss/mdss_livedisplay.c:249:22: error: 'CMD_CLK_CTRL' undeclared (first use in this function)
>      CMD_REQ_COMMIT | CMD_CLK_CTRL);

Due to: Due to: https://github.com/LineageOS/android_kernel_xiaomi_msm8996/commit/ef729840cb311820df67b687283651c8e21db3db. Removed CMD_CLK_CTRL flag as well from here.

Patch-set: 1
Label: Verified=0