cld: hdd: Fix compilation error in iw_set_pno()
RSSI threshold data type for PNO is changed to signed long in below commit,
  "cld: hdd: Handle RSSI threshold value passed in start sched_scan"

Due to this, compiler generated below error,

CORE/HDD/src/wlan_hdd_wext.c:7085:15: warning: format '%hhu'
expects argument of type 'unsigned char *', but argument 3 has type
'tANI_S32 *' [-Wformat] error, forbidden warning: wlan_hdd_wext.c:7085

Change-Id: I521d38794bb8bf164275d1843d431f2bad8e05f7
CRs-fixed: 567665