qcacld-2.0: fix a compilation error
If FEATURE_BUS_BANDWIDTH is not enabled, error
below happens when compiling cld driver:
"error: unused variable 'vos_timer_state'
 [-Werror=unused-variable]"
To fix this issue, define a static function to
de-initiate bus_bw_timer.

Change-Id: Ie681df995c362c70bb6abdf95e02310741c00c46
CRs-Fixed: 2202980